name: prototype
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.4.0
  dropdown_formfield: ^0.1.4
  email_validator: ^1.0.6
  modal_progress_hud: ^0.1.3
  shared_preferences: ^2.0.13
  fl_chart: ^0.35.0
  syncfusion_flutter_charts: ^19.4.53
  http: ^0.13.4
  rflutter_alert: ^2.0.4
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
